[project]
name = "version1-mini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asttokens==3.0.1",
    "certifi==2025.11.12",
    "charset-normalizer==3.4.4",
    "colorama==0.4.6",
    "comm==0.2.3",
    "contourpy==1.3.3",
    "cycler==0.12.1",
    "debugpy==1.8.19",
    "decorator==5.2.1",
    "executing==2.2.1",
    "filelock==3.20.1",
    "fonttools==4.61.1",
    "fsspec==2025.12.0",
    "idna==3.11",
    "ipykernel==7.1.0",
    "ipython==9.8.0",
    "ipython-pygments-lexers==1.1.1",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "joblib==1.5.3",
    "jupyter-client==8.7.0",
    "jupyter-core==5.9.1",
    "kiwisolver==1.4.9",
    "lap==0.5.12",
    "markupsafe==3.0.3",
    "matplotlib==3.10.8",
    "matplotlib-inline==0.2.1",
    "mpmath==1.3.0",
    "nest-asyncio==1.6.0",
    "networkx==3.6.1",
    "numpy==2.2.6",
    "opencv-python==4.12.0.88",
    "packaging==25.0",
    "pandas==2.3.3",
    "pandas-stubs==2.3.3.251219",
    "parso==0.8.5",
    "pillow==12.0.0",
    "platformdirs==4.5.1",
    "polars==1.36.1",
    "polars-runtime-32==1.36.1",
    "prompt-toolkit==3.0.52",
    "psutil==7.1.3",
    "pure-eval==0.2.3",
    "pygments==2.19.2",
    "pyparsing==3.2.5",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "pyyaml==6.0.3",
    "pyzmq==27.1.0",
    "requests==2.32.5",
    "scikit-learn==1.8.0",
    "scipy==1.16.3",
    "setuptools==80.9.0",
    "six==1.17.0",
    "stack-data==0.6.3",
    "sympy==1.14.0",
    "threadpoolctl==3.6.0",
    "torch==2.9.1",
    "torchvision==0.24.1",
    "tornado==6.5.4",
    "traitlets==5.14.3",
    "types-pytz==2025.2.0.20251108",
    "typing-extensions==4.15.0",
    "tzdata==2025.3",
    "ultralytics==8.3.240",
    "ultralytics-thop==2.0.18",
    "urllib3==2.6.2",
    "wcwidth==0.2.14",
]
